### PR TITLE
Fixed issue with getting room mods

### PR DESCRIPTION
**Pull request by donboricua**
Fixed an issue for getting room mods.

### CODE REVIEW

**Comment by piks** [comment]
definitly RIP, people seem to be converting over, sad to say if this lib completly dies the endless pastebin bots will be destroyed, At least till newer lib pastebins occur.

**Comment by Syncro9** [comment]
Eeeeh, but there are people like me who don't like change. What other alternative do we have anyway if this lib dies completely.

**Comment by piks** [comment]
@Syncro9 there is at least 3 other public chatango bot libs available, look around.

**Comment by danielisaksen** [comment]
ch.py will die, confirmed by Chatango staff. The Flash client + the socket servers are online only for the users who are on old browsers such as IE6. It will be phased out as soon as the HTML5+JS chat is close to fully completed.

As for other libraries, there are very few good Python alternatives. There's the obsolete and broken cellsheet/chlib, sorch/coco (I wrote it as a joke, from boredom at first, and it worked) and kamijoutouma/HerpLib (Python DerpLib (by makurayami/barrykun. They're b0rked, old and obsolete.

I mostly use libraries I've written myself.

**Comment by Syncro9** [comment]
Might as well just try to write my own then. ;_;

**Comment by danielisaksen** [comment]
Lawouach/WebSocket-for-Python works well.

**Comment by piks** [comment]
@danielisaksen i didnt think chlib was broken?, just not as maintained as before

**Comment by danielisaksen** [comment]
@piks In some ways broken. It still works, but certain features don't.

**Comment by asl97** [comment]
yay, ch.py will die along with all the pastebin bots!

in any case, take a close look at it,  the in-code documentation is outdated, it use a poorly design thread joining system (yes i know, i wrote it, but i didn't see another other way of doing it back then), people use time.sleep even though it is single thread and then complain that it doesn't work properly, and a whole lot of other problem.

i suppose you could thank/blame* @AcePokeMaster aka charles for making me angry and cause me to stop updating/"worsening"* this library, you could also blame/thank* him cause if it weren't for him, i might still be updating this library and keeping it alive like how i did it way back and a few people sure hated me for it (https://github.com/Nullspeaker/ch.py/commit/c99608217722a0adf1e8d7b197f1666764c99fe3).

*depending on how you look at it

ps:
i most likely wouldn't reply to any comment
i doubt anyone would be able convince me to patch it up again since i am tired of all the drama
i got better things to do than start another argument

**Comment by Syncro9** [comment]
And then there are people like me who don't know if there even was any drama or shit. I'm clueless af lel. I'm autistic and don't like change when everything is working fine.

**Comment by AcePokeMaster** [comment]
I didn't make you do anything. You allowed your emotions to get out of control. So the only person to blame is yourself. Thank you and good bye. :)

**Comment by danielisaksen** [comment]
@asl97 You shouldn't blame anyone else for your actions, nor let your emotions get out of swing like that. Do or don't. Either way, keep your drama out of the GitHub comment field, please.

The "current" ch.py is a mess, and shouldn't be used in that state. It's been broken down and duct taped back together by tons of non-programmers and aspirants. Some of the code is horrible, architecture and syntax wise.

I'll consider forking ch.py, but I don't want to keep all the ch.py bots alive.

**Pull request merged**
